CREATE TABLE IF NOT EXISTS book_searchs (
  id VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
  data JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
