ALTER TABLE users
ADD COLUMN subscription VARCHAR(50),
ADD COLUMN subscription_status VARCHAR(50),
ADD COLUMN subscription_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN subscription_end_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
